<a href="https://colab.research.google.com/github/SNSIMANTO/ML-Research-Lab/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SETUP


In [ ]:
import numpy as np
import pandas as pd
import warnings; warnings.filterwarnings('ignore')

print(f"NumPy .{np.__version__}\nPandas{np.__version__}")

NumPy .2.0.2
Pandas2.0.2


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])

print("a + b :", a+b)
print("a * b :", a*b)
print("a * a :", a*a)

print('sqrt(a) :', np.sqrt(a))

a + b : [ 8 10 12 14 16 18]
a * b : [ 7 16 27 40 55 72]
a * a : [ 1  4  9 16 25 36]
sqrt(a) : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


Broadcasting

In [ ]:
import numpy as np
m = np.array([[1,2,3,4,5],
            [10,20,30,40,50]])
n = np.array([90,80,70,60,50])

print(m+n)

[[ 91  82  73  64  55]
 [100 100 100 100 100]]


indexing and slicing

In [28]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,88])

print('arr[4] :',arr[4])
print('arr[1:4]:',arr[1:4])
print('arr[arr>2]',arr[arr>2])

M=np.array([[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8]])
print('M[:2] :',M[:2], sep='\n')
print('M[:,1] :',M[:,1])  #print the value of column 1

arr[4] : 5
arr[1:4]: [2 3 4]
arr[arr>2] [ 3  4  5  6  7  8 88]
M[:2] :
[[1 2 3 4 5 6]
 [2 3 4 5 6 7]]
M[:,1] : [2 3 4]
